name: Keep Streamlit Apps Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Apps
        run: |
          curl -s https://ai-meal-and-workout-planner-jgkqrpampgisnjfskpjttz.streamlit.app/
          curl -s https://heartattackriskpredictor.streamlit.app/
          
